name: Set Global Variables

outputs:
  EmailRecepient:
    value: ${{ steps.globals.outputs.EmailRecepient }}
  CICDkey:
    value: ${{ steps.globals.outputs.CICDkey }}

runs:
  using: composite

  steps:
    - name: Global variables
      shell: bash
      id: globals
      run: |
        chmod +x global.sh
        ./.github/actions/SetGlobalVariables/global.sh
