name: Set Global Var Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Global Vars
        id: global
        uses: ./.github/actions/SetGlobalVariables

      - name: Print variables
        run: echo ${{ steps.global.outputs.EmailRecepient }}
